apiVersion: v1
kind: Service
metadata:
  name: faraja-backend-svc
  namespace: faraja-ns
  labels: 
    app: faraja
spec:
  selector:
    app: faraja
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32767