apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faraja-pvc
  namespace: faraja-ns
  labels:
    app: postgres
    tier: database
    team: cne01
    project: faraja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
